### ISSUE TITLE
Making available on NPM?

### ISSUE THREAD

**Issue by agilgur5** [jacobdeichert/mask#104]
Since this replaces and is inspired by [`maidfile`](https://github.com/egoist/maid), it would be great if the binaries were available on NPM for ease of installation in JS projects.

`swc` is an example of a Rust project with [binaries available on NPM](https://github.com/swc-project/swc/blob/203b2297c3dbdc2ff66f09d96b5f3f2450217358/package.json#L150).

Could also be made available as WASM on NPM too

**Comment by jacobdeichert** [comment]
Although I do understand this would be more convenient in node-only environments, at this point in time I don't feel like maintaining an npm package for mask. It adds a lot of complexity to the release process and it requires precompiling binaries for many targets in order to download them post-install, as far as I know.

**Comment by agilgur5** [comment]
> it requires precompiling binaries for many targets in order to download them post-install, as far as I know.

More or less, yes. https://github.com/evanw/esbuild/pull/1621 is a good reference.
But the current release process already precompiles binaries for GH releases and Brew, no?

The simpler alternative that I mentioned is a WASM build, which is a single binary
